### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../../data/heat/GRFs_heat.mat'

### ISSUE THREAD

**Issue by memorycoffee** [HewlettPackard/separable-operator-networks#1]
Hi, I'm trying to run the 'heat.py', but i don't know how to get the 'GRFs_heat.mat'.

**Comment by smhooten** [comment]
Hi @memorycoffee, thanks for pointing it out. See the latest commits such as 802fc1e0b7eb7262dbd9ab236b59926914432d96. There is a new test data generation script in scripts/generate_test_data/heat.py, and I updated scripts/main_scripts/heat.py to load that data. 

btw you'll need to pip install diffrax for it to work.

**Comment by memorycoffee** [comment]
> Hi @memorycoffee, thanks for pointing it out. See the latest commits such as [802fc1e](https://github.com/HewlettPackard/separable-operator-networks/commit/802fc1e0b7eb7262dbd9ab236b59926914432d96). There is a new test data generation script in scripts/generate_test_data/heat.py, and I updated scripts/main_scripts/heat.py to load that data.
> 
> btw you'll need to pip install diffrax for it to work.

Thanks! I will try it.
